## Logistic region
![alt text](1_2IAHsCEZaZtZ9ybziYPDEQ-1.jpg)

In [35]:
import pandas as pd
import numpy as np

In [36]:
df = pd.read_excel(r"C:\Users\Prajwal D Hiretanad\Desktop\ML CERTI\tennis_anyone_1000.xlsx")

In [37]:
df.head()

  Day ID   Outlook Temperature Humidity    Wind Play Tennis
0  Day_1  Overcast        Cool   Normal  Strong         Yes
1  Day_2      Rain        Mild     High    Weak         Yes
2  Day_3  Overcast         Hot   Normal    Weak         Yes
3  Day_4     Sunny        Mild   Normal  Strong         Yes
4  Day_5     Sunny        Mild     High    Weak          No

In [38]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Outlook']=le.fit_transform(df['Outlook'])
df['Temperature']=le.fit_transform(df['Temperature'])
df['Humidity']=le.fit_transform(df['Humidity'])
df['Wind']=le.fit_transform(df['Wind'])
df['Play Tennis']=le.fit_transform(df['Play Tennis'])

In [39]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [40]:
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import RandomOverSampler

In [41]:
df = pd.read_csv("magic04.data")

In [42]:
columns=['fLength', 'fWidth', 'fSize', 'fConc', 'fConc1', 'fAsym', 'fM3Long', 'fM3Trans', 'fAlpha', 'fDist', 'class']

In [43]:
df.head()

,28.7967,16.0021,2.6449,0.3918,0.1982,27.7004,22.011,-8.2027,40.092,81.8828,g
0,31.6036,11.7235,2.5185,0.5303,0.3773,26.2722,23.8238,-9.9574,6.3609,205.261,g
1,162.0520,136.0310,4.0612,0.0374,0.0187,116.7410,-64.8580,-45.2160,76.9600,256.788,g
2,23.8172,9.5728,2.3385,0.6147,0.3922,27.2107,-6.4633,-7.1513,10.4490,116.737,g
3,75.1362,30.9205,3.1611,0.3168,0.1832,-5.5277,28.5525,21.8393,4.6480,356.462,g
4,51.6240,21.1502,2.9085,0.2420,0.1340,50.8761,43.1887,9.8145,3.6130,238.098,g

In [44]:
df.columns

Index(['28.7967', '16.0021', '2.6449', '0.3918', '0.1982', '27.7004', '22.011',
       '-8.2027', '40.092', '81.8828', 'g'],
      dtype='str')

In [ ]:
# ...existing code...
df.columns = columns
df["class"] = (df["class"] == "g").astype(int)
# ...existing code...

KeyError: 'class'

In [ ]:
df['class']

NameError: name 'df' is not defined

In [ ]:
train,valid,test = np.split(df.sample(frac=1),[int(0.6*len(df)),int(0.8*len(df))])

NameError: name 'df' is not defined

In [ ]:
train = pd.DataFrame(train)
valid = pd.DataFrame(valid)
test = pd.DataFrame(test)

NameError: name 'train' is not defined

In [ ]:
def scale_data(dataframe,oversample=False):
    x= dataframe[dataframe.columns[:-1]].values
    y= dataframe[dataframe.columns[-1]].values

    scaler=StandardScaler()
    x=  scaler.fit_transform(x)

    if oversample:
        ros= RandomOverSampler()
        x,y= ros.fit_resample(x,y)
    data= np.hstack((x,np.reshape(y,(-1,1))))

    return data,x, y

In [ ]:
train, X_train, y_train = scale_data(train, oversample=True)
valid, X_valid, y_valid = scale_data(valid, oversample=False)
test, X_test, y_test = scale_data(test, oversample=False)

NameError: name 'train' is not defined

In [ ]:
#### using logistic regression model
from sklearn.linear_model import LogisticRegression
lrc = LogisticRegression()
lrc.fit(X_train, y_train)

NameError: name 'X_train' is not defined

In [ ]:
predict = lrc.predict(X_test)

NameError: name 'X_test' is not defined

In [ ]:
### model evalution
from sklearn.metrics import classification_report
print(classification_report(y_test, predict))

NameError: name 'y_test' is not defined